 	CREATE TABLE `anamnese` (


`id_anamnese` int(11) NOT N
"nome"
"idade"
"data_nascimento"
"sexo"
"estado_civil"
"escolaridade"
"curso"
"faculdade"
"periodo"
"telefone"
"religiao"
"local_trabalho"
"naturalidade"
"endereco"
"nome_conjuge"
"idade_do_conjuge"
"profissao_do_conjuge"
"local_trabalho_do_conjuge"
"filhos"
"contato_emegerncia"
"queixa_principal"
"aparencia_paciente"
"como_se_comportou"
"atitude_para_com_psicologo"
"orientacao_discurso"
"senso_percepcao"
"pensamento_e_comunicacao"
"humor_no_momento"
"consciencia_da_doenca_ou_dificuldade_atual"
"inicio_da_patologia"
"frequencia_atual"
"itensidade"
"tratamento_e_medicamentos_psiquiatricos_anteriores"
"medicamentos_atuais"
"sintomas_apresentados_atualmente"
"eventos_traumaticos_de_vida"
"usa_ou_usou_droga"
"existiu_tentitiva_de_suicidio"
"nome_do_pai"
"idade_do_pai"
"profissão_do_pai"
"nome_da_mae"
"idade_da_mae"
"profissao_da_mae"
"numero_de_irmaos"
"reside_com"
"estado_civil_dos_pais"
"tempo_pais_separados"
"voce_e_filho"
"idade_adocao"
"e_de_sua_adocao"
"sua_reacao_adocao"
"alguem_com_transtorno_psiquiatrico"
"qual_quem_com_transtorno_psiquiatrico"
"alguem_com_vicio"
"qual_quem_com_vicio"
"com_tiques"
"qual_quem_com_tiques"
"vai_bem_curso_trabalho"
"dificuldade_relacionar_se"
"quais_dificuldades"
"faz_amigo_com_dificuldade"
"adapta_se_facilmente_ao_meio"
"prefere_ficar_so_ou_com_amigo"
"participa_de_atividade_extra"
"quais_atividades"
"descricao_rotina"
"possui_doencas"
"passou_por_aplicacao_de_teste"
"descricao_relacionamentos"
"relacao_com_mae"
"ralacao_com_pai"
"relacao_com_irmao"
"relacao_com_filhos"
"relacao_com_parceiro"
"vida_sexual"


 PRIMARY KEY (`id_anamnese`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci